version: "3.9"
services:

  rabbit-kafka-bridge:
    build: 
      context: "."
    image: exaspace/rabbit-kafka-bridge
    depends_on:
      - rabbitmq
      - kafka
    command: >
      --rabbit_host rabbitmq --rabbit_queue testqueue --kafka_host kafka --kafka_topic testtopic

  rabbitmq:
    image: rabbitmq:3.11.4-management
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-test-config:/etc/rabbitmq

  kafka:
    hostname: kafka
    image: docker.io/bitnami/kafka:3.3
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  zookeeper:
     image: docker.io/bitnami/zookeeper:3.8
     ports:
       - '2181:2181'
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
