version: '2'
services:

  rabbit-kafka-bridge:
    image: exaspace/rabbit-kafka-bridge
    depends_on:
      - rabbitmq
      - kafka
    command: >
      --rabbit_host rabbitmq --rabbit_queue testqueue --kafka_host kafka --kafka_topic testtopic

  rabbitmq:
    image: rabbitmq:3.7.15-management
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-config:/etc/rabbitmq

  kafka:
    image: 'bitnami/kafka:2.2.1'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  zookeeper:
    image: 'bitnami/zookeeper:3.5.5'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

