name: Test
on:

  workflow_dispatch:

  push:
    branches:
      - 'master'

jobs:
  
  test:
  
    runs-on: ubuntu-latest
    steps:

      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Test"
        run: |
          pip install -r requirements.txt
          make test
