name: Test
on:

  workflow_dispatch:

  push:
    branches:
      - 'master'

jobs:
  
  test:
  
    runs-on: ubuntu-latest
    steps:

      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Build docker image"
        run: |
          docker compose build --no-cache

      - name: "Pull docker images for test dependencies"
        run: |
          docker compose pull rabbitmq kafka

      - name: "Integration Test"
        run: |
          docker compose up -d
          sleep 10
          docker compose exec  -e KAFKA_HOST=kafka -e RABBIT_HOST=rabbitmq rabbit-kafka-bridge make test
          docker compose down -v
